# Generated by Django 3.0.5 on 2020-05-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUploadModel',
            new_name='ImageModel',
        ),
    ]
