# Generated by Django 3.0.2 on 2020-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0005_detectionmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionmodel',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
